version: '3'
services:
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - .data/pg:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
